"""
Selection-aware shrinkage backtest on the 2025-26 production pool. Read-only; writes nothing to S3.

The pool is what our lineups actually chose from: players complex projected > 0 and on the DFF slate. FP_HAT is
barebones FP regenerated by scripts/backtest_fp_rate.py's code (trained on 2022-25, serving features as of each
slate, fed the stored complex minutes), because production only stored FP projections from January 2026. Each variant pulls FP_HAT toward the
player's own season FP average (S_FP, from the replay table):

    adjusted = S_FP + k * (FP_HAT - S_FP)

k is fit by least squares on the deviations (actual - S_FP ~ k * (FP_HAT - S_FP)), either one k for everyone or one
per risk group. Fitting is cross-fitted by time: k learned on the first half of the slates is scored on the second
half and vice versa. Lineups are rebuilt with the production optimizer.

Scored on: "what picking adds" (picked players' projection - actual, minus the pool's) and realized lineup FP.

Needs data/replay/replay.parquet (scripts/build_replay.py).
Usage: python scripts/backtest_shrinkage.py
"""

import io
import logging
import sys
from pathlib import Path

import boto3
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "lambda" / "minutes-projection"))
from lineup_optimizer import calculate_fp_features, optimize_lineup  # noqa: E402
sys.path.insert(0, str(ROOT / "scripts"))
import backtest_fp_rate as fp  # noqa: E402

logging.getLogger().setLevel(logging.ERROR)
BUCKET = "nba-prediction-ibracken"
GROUPS = ["injury boost", "missed recent games", "under 10 games", "bench", "everyone else"]


def load(key):
    s3 = boto3.client("s3")
    return pd.read_parquet(io.BytesIO(s3.get_object(Bucket=BUCKET, Key=key)["Body"].read()))


def build_pool():
    cx = load("model_comparison/complex_position_overlap/minutes_projections.parquet")
    fc = load("model_comparison/formula_c_baseline/minutes_projections.parquet")
    daily = load("data/daily_predictions/current.parquet")
    for d, col in ((cx, "DATE"), (fc, "DATE"), (daily, "GAME_DATE")):
        d["D"] = pd.to_datetime(d[col]).dt.normalize()
    cx = cx[(cx.D >= "2025-10-01") & (cx.D <= "2026-04-12") & (cx.PROJECTED_MIN > 0)].drop_duplicates(["D", "PLAYER"])
    pool = cx[["D", "PLAYER", "TEAM", "PROJECTED_MIN"]].copy()
    pool = pool.merge(fc.drop_duplicates(["D", "PLAYER"])[["D", "PLAYER", "PROJECTED_MIN"]]
                      .rename(columns={"PROJECTED_MIN": "FC_PROD"}), on=["D", "PLAYER"], how="left")
    slate = daily.drop_duplicates(["D", "PLAYER"])[["D", "PLAYER", "SALARY", "POSITION", "STARTER_STATUS"]]
    pool = pool.merge(slate, on=["D", "PLAYER"], how="inner")

    replay = pd.read_parquet(ROOT / "data" / "replay" / "replay.parquet")
    replay = replay[replay.SEASON == "2025-26"][["D", "PLAYER", "S_FP", "GP", "TEAM_GAMES_MISSED", "ACT_FP", "PLAYED"]]
    pool = pool.merge(replay, on=["D", "PLAYER"], how="left")

    box = load("data/box_scores/2025-26.parquet")
    box["D"] = pd.to_datetime(box["GAME_DATE"]).dt.normalize()
    actual = box.groupby(["D", "PLAYER"])["FP"].sum()
    pool["ACT"] = [actual.get((d, p), 0.0) for d, p in zip(pool.D, pool.PLAYER)]   # did not play = 0

    bump = (pool.PROJECTED_MIN - pool.FC_PROD).fillna(0)
    pool["GROUP"] = np.select(
        [bump >= 0.5, pool.TEAM_GAMES_MISSED.fillna(0) >= 1, pool.GP.fillna(0) < 10, pool.STARTER_STATUS.isna()],
        GROUPS[:4], GROUPS[4])
    pool["HAS_PRIOR"] = pool.S_FP.notna() & (pool.S_FP > 0)

    pool["FP_HAT"] = regenerate_fp(pool, box)
    return pool


def regenerate_fp(pool, box_test):
    """Barebones FP for every pool row: model trained on 2022-25, features as of each slate, complex minutes."""
    hist = pd.concat([fp.load(f"data/box_scores/{s}.parquet") for s in fp.TRAIN_SEASONS], ignore_index=True)
    hist["GAME_DATE"] = pd.to_datetime(hist["GAME_DATE"])
    model = {"barebones": fp.train_old(fp.training_frame(hist), "barebones", 0)}
    box_test = box_test.copy()
    box_test["GAME_DATE"] = pd.to_datetime(box_test["GAME_DATE"])
    home = {d: dict(zip(g["TEAM_ABBREVIATION"], g["MATCHUP"].str.contains(" vs. ").astype(int)))
            for d, g in box_test.groupby("D")}
    out = pd.Series(np.nan, index=pool.index)
    for day, d in pool.groupby("D"):
        feats = calculate_fp_features(box_test[box_test["GAME_DATE"] < day], day.date()).drop_duplicates("PLAYER")
        frame = fp.serving_frame(feats, d[["PLAYER", "TEAM", "PROJECTED_MIN"]].reset_index(), home.get(day, {}))
        out.loc[frame["index"].values] = fp.predict(model, frame, frame["PROJECTED_MIN"])["barebones"]
    return out


def fit_k(df, by_group):
    d = df[df.HAS_PRIOR]
    dev_hat, dev_act = d.FP_HAT - d.S_FP, d.ACT - d.S_FP
    if not by_group:
        return {g: float((dev_hat * dev_act).sum() / (dev_hat ** 2).sum()) for g in GROUPS}
    out = {}
    for g in GROUPS:
        m = d.GROUP == g
        out[g] = float((dev_hat[m] * dev_act[m]).sum() / (dev_hat[m] ** 2).sum()) if m.sum() > 30 else 1.0
    return out


def adjust(df, k):
    kk = df.GROUP.map(k).where(df.HAS_PRIOR, 1.0)
    return np.where(df.HAS_PRIOR, df.S_FP + kk * (df.FP_HAT - df.S_FP), df.FP_HAT)


def lineups(pool, daily, col):
    rows = []
    for day, d in pool.groupby("D"):
        inp = d[["PLAYER", "TEAM", "POSITION", "PROJECTED_MIN"]].assign(PROJECTED_FP=d[col].values)
        lu = optimize_lineup(inp, daily, day.date())
        if len(lu) != 8:
            continue
        picked = d[d.PLAYER.isin(lu.PLAYER)]
        rows.append({"D": day, "REAL": picked.ACT.sum(), "PROJ": picked[col].sum(),
                     "PICK_OVER": (picked[col] - picked.ACT).mean(), "POOL_OVER": (d[col] - d.ACT).mean(),
                     "PICK_SFP_OVER": (picked.S_FP - picked.ACT).mean(), "POOL_SFP_OVER": (d.S_FP - d.ACT).mean(),
                     "PLAYERS": tuple(sorted(picked.PLAYER))})
    return pd.DataFrame(rows)


def bootstrap(v, n=4000, seed=0):
    v = np.asarray(v)
    m = np.random.default_rng(seed).choice(v, (n, len(v))).mean(axis=1)
    return v.mean(), np.percentile(m, 2.5), np.percentile(m, 97.5)


def main():
    pool = build_pool()
    daily = load("data/daily_predictions/current.parquet")
    daily["GAME_DATE"] = pd.to_datetime(daily["GAME_DATE"]).dt.date
    days = sorted(pool.D.unique())
    half = days[len(days) // 2]
    first, second = pool[pool.D < half], pool[pool.D >= half]
    print(f"Pool: {len(pool):,} player-slates over {len(days)} slates; with a season-average prior "
          f"{pool.HAS_PRIOR.mean():.1%}")
    print("Group sizes:", pool.GROUP.value_counts().to_dict())

    variants = {"no shrink": None, "one k": False, "k per group": True}
    results = {}
    for name, by_group in variants.items():
        parts = []
        for fit_on, test_on in ((first, second), (second, first)):
            test = test_on.copy()
            if by_group is None:
                test["ADJ"] = test.FP_HAT
            else:
                k = fit_k(fit_on, by_group)
                test["ADJ"] = adjust(test, k)
                print(f"  {name}: k fit on {'first' if fit_on is first else 'second'} half ->",
                      {g: round(v, 2) for g, v in k.items()} if by_group else round(k[GROUPS[0]], 2))
            parts.append(test)
        scored = pd.concat(parts)
        results[name] = (scored, lineups(scored, daily, "ADJ"))

    print("\n=== Results (each half scored with k fit on the other half) ===")
    base = results["no shrink"][1].set_index("D")
    for name, (scored, lu) in results.items():
        e = scored.ADJ - scored.ACT
        lu = lu.set_index("D")
        print(f"\n{name}: player MAE {np.abs(e).mean():.3f}, bias {e.mean():+.3f} | {len(lu)} lineups")
        print(f"  what picking adds: {(lu.PICK_OVER - lu.POOL_OVER).mean():+.2f} FP per slot "
              f"(picked over {lu.PICK_OVER.mean():+.2f}, pool over {lu.POOL_OVER.mean():+.2f})")
        print(f"  picked players' own season avg vs actual: {lu.PICK_SFP_OVER.mean():+.2f} (pool {lu.POOL_SFP_OVER.mean():+.2f})")
        print(f"  realized lineup FP: mean {lu.REAL.mean():.1f}, median {lu.REAL.median():.1f}; "
              f"projected {lu.PROJ.mean():.1f}")
        if name != "no shrink":
            common = lu.index.intersection(base.index)
            mean, lo, hi = bootstrap(lu.loc[common, "REAL"] - base.loc[common, "REAL"])
            changed = (lu.loc[common, "PLAYERS"] != base.loc[common, "PLAYERS"]).mean()
            print(f"  vs no shrink: {mean:+.1f} realized FP per lineup (95% CI {lo:+.1f}..{hi:+.1f}); "
                  f"lineup changed on {changed:.0%} of slates")


if __name__ == "__main__":
    main()
