from sqlalchemy import Column, Integer, String, Float
from config import Base

class AdvancedPlayerStats(Base):
    __tablename__ = "advancedPlayerStats"

    id = Column(Integer, primary_key=True, autoincrement=True)
    PLAYER = Column(String, primary_key = True nullable=False)
    TEAM = Column(String, nullable=False)
    AGE = Column(Integer, nullable=False)
    GP = Column(Integer)
    W = Column(Integer)
    L = Column(Integer)
    MIN = Column(Float)
    OFFRTG = Column(Float)
    DEFRTG = Column(Float)
    NETRTG = Column(Float)
    AST_PERCENT = Column(Float)
    AST_TO = Column(Float)
    AST_RATIO = Column(Float)
    OREB_PERCENT = Column(Float)
    DREB_PERCENT = Column(Float)
    REB_PERCENT = Column(Float)
    TO_RATIO = Column(Float)
    EFG_PERCENT = Column(Float)
    TS_PERCENT = Column(Float)
    USG_PERCENT = Column(Float)
    PACE = Column(Float)
    PIE = Column(Float)
    POSS = Column(Integer)
    FGA2P_PERCENT = Column(Float)
    FGA3P_PERCENT = Column(Float)
    PTS2P_PERCENT = Column(Float)
    PTS2P_MR_PERCENT = Column(Float)
    PTS3P_PERCENT = Column(Float)
    PTSFBPS_PERCENT = Column(Float)
    PTSFT_PERCENT = Column(Float)
    PTS_OFFTO_PERCENT = Column(Float)
    PTSPITP_PERCENT = Column(Float)
    FG2M_AST_PERCENT = Column(Float)
    FG2M_UAST_PERCENT = Column(Float)
    FG3M_AST_PERCENT = Column(Float)
    FG3M_UAST_PERCENT = Column(Float)
    FGM_AST_PERCENT = Column(Float)
    FGM_UAST_PERCENT = Column(Float)
    DEF_RTG = Column(Float)
    DREB = Column(Float)
    DREB_PERCENT_TEAM = Column(Float)
    STL = Column(Float)
    STL_PERCENT = Column(Float)
    BLK = Column(Float)
    BLK_PERCENT = Column(Float)
    OPP_PTS_OFFTO = Column(Float)
    OPP_PTS_2ND_CHANCE = Column(Float)
    OPP_PTS_FB = Column(Float)
    OPP_PTS_PAINT = Column(Float)
    DEFWS = Column(Float)


class ClusteredPlayers(Base):
    __tablename__ = "ClusteredPlayers"
    id = Column(Integer, primary_key=True, autoincrement=True)
    PLAYER = Column(String, nullable=False)
    CLUSTER = Column(String, nullable=False)